import { ENTITY_TYPE_LABELS, TYPE_LABELS, type ActiveAlertType } from './alerts'

export type AlertRuleDomain = 'Operação' | 'Revisão' | 'Financeiro' | 'Portal'
export type AlertRuleDepartment = 'documentacao' | 'equipamentos' | 'operacoes'
export type AlertRuleSeverity = 'critical' | 'normal'

export type AlertRule = {
  type: ActiveAlertType
  label: string
  domain: AlertRuleDomain
  department: AlertRuleDepartment
  entityType: keyof typeof ENTITY_TYPE_LABELS
  severity: AlertRuleSeverity
  summary: string
  trigger: string
  timing: string
  resolution: string
  destination: string
  destinationLabel: string
  afterResolution: string
  dismissal: string
}

type AlertRuleDraft = Omit<AlertRule, 'label'>

const temporaryDismissal = 'Pode ser dispensado temporariamente na fila, com motivo obrigatório e data futura de revisão. A dispensa não corrige a origem nem libera um bloqueio.'
const derivedResolution = 'O alerta é fechado automaticamente quando a origem é corrigida e a reconciliação confirma que a pendência deixou de existir.'

const ALERT_RULES_BASE = [
  {
    type: 'review_customer_unlinked',
    domain: 'Revisão',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'O B/L está aguardando revisão, mas ainda não foi vinculado a um cliente.',
    trigger: 'B/L com status de revisão pendente e sem cliente associado.',
    timing: 'Aparece imediatamente enquanto a revisão permanecer pendente.',
    resolution: 'Vincule o B/L ao cliente correto na fila de Revisão.',
    destination: '/revisao',
    destinationLabel: 'Abrir Revisão',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'review_customer_email_missing',
    domain: 'Revisão',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'O B/L tem cliente, mas o cadastro não possui um e-mail de contato utilizável.',
    trigger: 'Cliente vinculado ao B/L sem contato com e-mail preenchido.',
    timing: 'Aparece durante a revisão pendente e some quando um e-mail válido é cadastrado.',
    resolution: 'Cadastre ou corrija o contato do cliente e conclua a revisão do B/L.',
    destination: '/revisao',
    destinationLabel: 'Abrir Revisão',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'review_portal_not_ready',
    domain: 'Revisão',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'O cliente do B/L ainda não tem uma conta de Portal pronta para uso.',
    trigger: 'Cliente vinculado, mas sem conta ativa do Portal com usuário provisionado.',
    timing: 'Aparece durante a revisão pendente até a conta do Portal estar pronta.',
    resolution: 'Abra a gestão do Portal, regularize a conta do cliente e depois conclua a revisão.',
    destination: '/clientes/portal',
    destinationLabel: 'Abrir Clientes e Portal',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'review_breakbulk_weight_missing',
    domain: 'Revisão',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'Um B/L de carga solta está sem peso informado para seguir na revisão.',
    trigger: 'B/L de carga solta com peso ausente ou menor que o valor mínimo aceito.',
    timing: 'Aparece enquanto o B/L permanecer em revisão pendente.',
    resolution: 'Informe o peso correto da carga solta e confirme a revisão.',
    destination: '/revisao',
    destinationLabel: 'Abrir Revisão',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'review_granite_customer_unlinked',
    domain: 'Revisão',
    department: 'documentacao',
    entityType: 'granite_bl',
    severity: 'critical',
    summary: 'O B/L de Granito foi recebido sem cliente vinculado.',
    trigger: 'Registro de Granito sem cliente associado.',
    timing: 'Aparece assim que o registro é criado ou alterado sem vínculo.',
    resolution: 'Associe o registro de Granito ao cliente correto na revisão.',
    destination: '/revisao',
    destinationLabel: 'Abrir Revisão',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'billing_calculation_blocked',
    domain: 'Financeiro',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'O cálculo das Taxas Locais de um B/L não conseguiu avançar.',
    trigger: 'O motor de cobrança encontra uma pendência que impede o cálculo.',
    timing: 'Aparece no momento do cálculo e permanece até a causa ser corrigida.',
    resolution: 'Siga a correção indicada no alerta e revise o cálculo na operação de Taxas Locais.',
    destination: '/taxas-locais',
    destinationLabel: 'Abrir Taxas Locais',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'billing_auto_issue_failed',
    domain: 'Financeiro',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'A emissão automática de uma cobrança falhou e precisa de conferência.',
    trigger: 'Uma tentativa automática de emitir o documento financeiro termina com erro.',
    timing: 'Aparece após a falha da emissão automática.',
    resolution: 'Abra a operação de Taxas Locais, corrija a pendência e faça a emissão controlada.',
    destination: '/taxas-locais',
    destinationLabel: 'Abrir Taxas Locais',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'invoice_overdue',
    domain: 'Financeiro',
    department: 'documentacao',
    entityType: 'invoice',
    severity: 'normal',
    summary: 'Uma fatura ultrapassou o vencimento sem a baixa esperada.',
    trigger: 'A data de vencimento passou e a fatura continua em aberto.',
    timing: 'Começa a aparecer depois do vencimento, enquanto a fatura não for regularizada.',
    resolution: 'Confirme o recebimento, a baixa ou a tratativa financeira correspondente.',
    destination: '/taxas-locais',
    destinationLabel: 'Abrir Taxas Locais',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'invoice_payment_invalid',
    domain: 'Financeiro',
    department: 'documentacao',
    entityType: 'invoice',
    severity: 'critical',
    summary: 'O pagamento recebido não pôde ser validado contra a fatura.',
    trigger: 'A conciliação identifica dados ou valores incompatíveis com a fatura.',
    timing: 'Aparece quando a validação do pagamento falha.',
    resolution: 'Confira o pagamento e faça a correção ou conciliação segura na operação financeira.',
    destination: '/taxas-locais',
    destinationLabel: 'Abrir Taxas Locais',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'invoice_cancel_blocked',
    domain: 'Financeiro',
    department: 'documentacao',
    entityType: 'invoice',
    severity: 'critical',
    summary: 'Uma tentativa de cancelar a fatura foi bloqueada por uma condição financeira.',
    trigger: 'O estado ou os vínculos da fatura não permitem cancelamento direto.',
    timing: 'Aparece quando a operação de cancelamento é recusada.',
    resolution: 'Analise o estado da fatura e siga o fluxo de cancelamento ou reemissão indicado.',
    destination: '/taxas-locais',
    destinationLabel: 'Abrir Taxas Locais',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'pix_unreconciled',
    domain: 'Financeiro',
    department: 'documentacao',
    entityType: 'pix_transaction',
    severity: 'critical',
    summary: 'Um PIX não encontrou uma correspondência segura com a cobrança esperada.',
    trigger: 'A transação não pode ser associada automaticamente a um recebível confiável.',
    timing: 'Aparece após a importação ou tentativa de conciliação do PIX.',
    resolution: 'Investigue a transação e confirme a correspondência na Conciliação PIX.',
    destination: '/reconciliacao',
    destinationLabel: 'Abrir Conciliação PIX',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_dispute_opened',
    domain: 'Portal',
    department: 'equipamentos',
    entityType: 'demurrage_invoice',
    severity: 'normal',
    summary: 'Um cliente abriu uma disputa sobre uma invoice de Demurrage.',
    trigger: 'A conversa de disputa é aberta no Portal para uma invoice de Demurrage.',
    timing: 'Aparece enquanto a disputa estiver aberta e aguardando tratamento interno.',
    resolution: 'Leia a conversa, analise os documentos e responda ou resolva a disputa em Demurrage.',
    destination: '/demurrage',
    destinationLabel: 'Abrir Demurrage',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_pendencia_geral',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'customer',
    severity: 'normal',
    summary: 'Existe um processo ativo, mas o Portal do cliente não está plenamente utilizável.',
    trigger: 'Cliente com B/L ativo sem Portal ativo, sem usuário provisionado ou sem e-mail de recuperação válido.',
    timing: 'É reavaliado pelo reconciliador do Portal enquanto houver processo ativo.',
    resolution: 'Regularize a conta e o e-mail de recuperação do cliente na gestão do Portal.',
    destination: '/clientes/portal',
    destinationLabel: 'Abrir Clientes e Portal',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_convite_expirado',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'customer',
    severity: 'normal',
    summary: 'O convite do Portal do cliente expirou antes da ativação.',
    trigger: 'A conta do cliente permanece com situação de convite expirado.',
    timing: 'Aparece durante processo ativo até que o convite seja renovado ou a conta regularizada.',
    resolution: 'Abra o cliente, confirme os dados e reenvie o convite do Portal.',
    destination: '/clientes/portal',
    destinationLabel: 'Abrir Clientes e Portal',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_falha_envio',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'customer',
    severity: 'normal',
    summary: 'O envio do convite do Portal falhou.',
    trigger: 'A conta do cliente fica com situação de falha no envio.',
    timing: 'Aparece enquanto o processo estiver ativo e o convite não for reenviado com sucesso.',
    resolution: 'Revise o e-mail do cliente e reenvie o convite pela gestão do Portal.',
    destination: '/clientes/portal',
    destinationLabel: 'Abrir Clientes e Portal',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_email_suprimido',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'customer',
    severity: 'normal',
    summary: 'O e-mail de recuperação está suprimido ou não pode ser usado.',
    trigger: 'O e-mail tem status diferente de utilizável ou aparece na lista de endereços suprimidos.',
    timing: 'Aparece enquanto houver processo ativo e o endereço continuar bloqueado.',
    resolution: 'Escolha e confirme um endereço de recuperação utilizável na gestão do Portal.',
    destination: '/clientes/portal',
    destinationLabel: 'Abrir Clientes e Portal',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_abuso_login',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'customer',
    severity: 'critical',
    summary: 'O padrão de tentativas de login exige investigação de segurança.',
    trigger: 'O sistema registra evidências de abuso ou tentativas anormais de acesso no Portal.',
    timing: 'Aparece quando o evento de segurança é registrado.',
    resolution: 'Investigue as evidências, proteja a conta e registre a tratativa de segurança.',
    destination: '/clientes/portal',
    destinationLabel: 'Abrir Clientes e Portal',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_excecao_critica_fatura',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'Uma invoice foi emitida sem que o Portal do cliente estivesse apto a recebê-la.',
    trigger: 'Invoice emitida para B/L cujo gate do Portal não está permitido.',
    timing: 'Aparece na emissão e permanece até a fatura sair do estado que mantém a exceção.',
    resolution: 'Abra o B/L na aba Financeiro, regularize o gate do Portal e trate a fatura.',
    destination: '/manifestos',
    destinationLabel: 'Abrir B/Ls CNTR',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'portal_reprocessamento_falhou',
    domain: 'Portal',
    department: 'documentacao',
    entityType: 'bl',
    severity: 'critical',
    summary: 'O faturamento de um B/L falhou ao ser reprocessado depois da ativação do Portal.',
    trigger: 'O reprocessamento pós-ativação termina com falha técnica não recuperada.',
    timing: 'Aparece durante o reprocessamento automático após a ativação do Portal.',
    resolution: 'Abra o B/L na aba Financeiro, analise o erro e faça a correção financeira necessária.',
    destination: '/manifestos',
    destinationLabel: 'Abrir B/Ls CNTR',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_bl_expected',
    domain: 'Operação',
    department: 'documentacao',
    entityType: 'voyage',
    severity: 'critical',
    summary: 'A viagem chegou à janela de conferência e ainda faltam B/Ls esperados.',
    trigger: 'Atinge D-7 do primeiro ETA brasileiro e as rotas esperadas não estão cobertas por B/Ls.',
    timing: 'Começa em D-7 do primeiro ETA brasileiro elegível e é recalculado até a cobertura completa.',
    resolution: 'Confira a viagem e importe ou corrija os B/Ls que faltam nas rotas esperadas.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_baplie_missing',
    domain: 'Operação',
    department: 'documentacao',
    entityType: 'voyage',
    severity: 'critical',
    summary: 'A viagem entrou na janela de conferência sem nenhum Baplie registrado.',
    trigger: 'Atinge D-7 do primeiro ETA brasileiro e não há containers Baplie para a viagem.',
    timing: 'Começa em D-7 e desaparece quando um Baplie é importado.',
    resolution: 'Importe o arquivo Baplie correto e revise o resultado da importação.',
    destination: '/baplie',
    destinationLabel: 'Abrir Baplie EDI',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_baplie_documentary_coverage',
    domain: 'Operação',
    department: 'documentacao',
    entityType: 'voyage',
    severity: 'critical',
    summary: 'Há divergência documental entre o Baplie e os B/Ls da viagem.',
    trigger: 'Depois da janela de cobertura, rotas ou containers do Baplie não correspondem aos B/Ls.',
    timing: 'Divergências de rota só passam a alertar em D-7; divergências encontradas depois são reconciliadas continuamente.',
    resolution: 'Abra o Baplie, compare os containers e corrija o documento ou o B/L na origem correta.',
    destination: '/baplie',
    destinationLabel: 'Abrir Baplie EDI',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_ce_mercante_missing',
    domain: 'Operação',
    department: 'documentacao',
    entityType: 'voyage',
    severity: 'critical',
    summary: 'Existem B/Ls da viagem sem CE Mercante informado.',
    trigger: 'Atinge D-5 do primeiro ETA brasileiro e pelo menos um B/L continua sem CE Mercante.',
    timing: 'Começa em D-5 e é recalculado conforme os CEs são preenchidos.',
    resolution: 'Abra a viagem, identifique os B/Ls afetados e informe os CEs Mercante corretos.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_schedule_date_pending',
    domain: 'Operação',
    department: 'operacoes',
    entityType: 'voyage_pod_schedule',
    severity: 'normal',
    summary: 'Uma escala ainda não tem todas as datas compartilhadas necessárias.',
    trigger: 'A escala elegível está sem ATA, ETB ou ETD conforme o ciclo da operação.',
    timing: 'É recalculado quando a rota ou as datas da escala mudam.',
    resolution: 'Abra a viagem e complete as datas que pertencem à escala.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_terminal_date_pending',
    domain: 'Operação',
    department: 'operacoes',
    entityType: 'voyage_escala_terminal',
    severity: 'normal',
    summary: 'Uma atracação ainda não tem as datas próprias do terminal completas.',
    trigger: 'A atracação está sem ATB ou ATD no ciclo do terminal.',
    timing: 'É recalculado quando as datas do terminal são informadas ou alteradas.',
    resolution: 'Abra a viagem e complete as datas ATB/ATD da atracação correspondente.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'voyage_export_after_atd',
    domain: 'Operação',
    department: 'operacoes',
    entityType: 'voyage_escala_terminal',
    severity: 'normal',
    summary: 'A escala já tem ATD, mas ainda existe planejamento de exportação pendente.',
    trigger: 'Após o ATD do terminal, permanecem dados obrigatórios de exportação sem conclusão.',
    timing: 'Começa após o ATD e permanece até o planejamento ser concluído ou corrigido.',
    resolution: 'Abra a viagem e conclua ou corrija o planejamento de exportação da escala.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'agency_report_department_pending',
    domain: 'Operação',
    department: 'documentacao',
    entityType: 'agency_departure_report',
    severity: 'normal',
    summary: 'Uma seção do ADR ainda aguarda a decisão do departamento responsável.',
    trigger: 'A seção do ADR permanece pendente após o ciclo operacional aplicável.',
    timing: 'Passa a ser relevante após o ATD da escala e é reavaliado a cada sign-off.',
    resolution: 'Abra o ADR, revise a seção do seu departamento e marque Confirmado ou Nada a declarar.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens / ADR',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
  {
    type: 'agency_report_deadline_missed',
    domain: 'Operação',
    department: 'documentacao',
    entityType: 'agency_departure_report',
    severity: 'critical',
    summary: 'O prazo de conclusão do ADR venceu com uma pendência ainda aberta.',
    trigger: 'O ATD iniciou o prazo do ADR e a data-limite foi ultrapassada sem resolução completa.',
    timing: 'Começa depois do vencimento do prazo calculado a partir do ATD.',
    resolution: 'Abra o ADR, trate a pendência do departamento e conclua os sign-offs necessários.',
    destination: '/viagens',
    destinationLabel: 'Abrir Viagens / ADR',
    afterResolution: derivedResolution,
    dismissal: temporaryDismissal,
  },
] satisfies AlertRuleDraft[]

export const ALERT_RULES: AlertRule[] = ALERT_RULES_BASE.map((rule) => ({
  ...rule,
  label: TYPE_LABELS[rule.type],
  // Mantém o rótulo técnico em um único lugar e permite que a busca encontre
  // tanto o nome humano quanto a descrição educativa.
  summary: `${TYPE_LABELS[rule.type]}: ${rule.summary}`,
}))

export const ALERT_RULE_DOMAINS: AlertRuleDomain[] = ['Operação', 'Revisão', 'Financeiro', 'Portal']

export const ALERT_RULE_DEPARTMENT_LABELS: Record<AlertRuleDepartment, string> = {
  documentacao: 'Documentação',
  equipamentos: 'Equipamentos',
  operacoes: 'Operações',
}

export const ALERT_RULE_SEVERITY_LABELS: Record<AlertRuleSeverity, string> = {
  critical: 'Crítico',
  normal: 'Normal',
}

export const ALERT_RULE_DOMAIN_DESCRIPTIONS: Record<AlertRuleDomain, string> = {
  Operação: 'Viagens, escalas, terminais e ADRs.',
  Revisão: 'Pendências que impedem a revisão de documentos e cadastros.',
  Financeiro: 'Cobranças, pagamentos e conciliação.',
  Portal: 'Eventos do Portal tratados pela equipe interna.',
}
