import { useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { Download, Upload } from 'lucide-react'
import { Button } from '../components/ui/Button'
import { Card, EmptyState, InlineError, PageHeader } from '../components/ui/Card'
import { Field, Input, Select } from '../components/ui/Input'
import { Modal } from '../components/ui/Modal'
import { useToast } from '../components/ui/Toast'
import { VoyageCombobox } from '../components/shared/VoyageCombobox'
import { useAuth } from '../hooks/useAuth'
import { listDepots, listCurrentDepotServices } from '../services/depots'
import { computeOperationTotals } from '../services/vaziosCusto'
import { getVaziosExportOperation, upsertOperationServiceQty } from '../services/vaziosExportOperations'
import { importVaziosManifest, listVaziosBookings, parseVaziosManifestFile, type ParsedVaziosManifest } from '../services/vaziosImport'
import { formatBRL, formatDate } from '../lib/utils'

export function EmbarqueVazios() {
  const { user, can } = useAuth(); const queryClient = useQueryClient(); const { showToast } = useToast()
  const canEdit = can('vazios_edit'); const [voyageId, setVoyageId] = useState(''); const [search, setSearch] = useState(''); const [port, setPort] = useState(''); const [tab, setTab] = useState<'containers' | 'costs'>('containers'); const [importOpen, setImportOpen] = useState(false); const [file, setFile] = useState<File | null>(null); const [uploadPort, setUploadPort] = useState(''); const [preview, setPreview] = useState<ParsedVaziosManifest | null>(null); const [qtyDrafts, setQtyDrafts] = useState<Record<string, string>>({})
  const bookings = useQuery({ queryKey: ['vazios-bookings', voyageId, search], queryFn: () => listVaziosBookings({ voyageId, search, page: 1, pageSize: 100 }), enabled: Boolean(voyageId) })
  const rows = bookings.data?.rows ?? []; const ports = [...new Set(rows.map((row) => row.embark_port).filter(Boolean) as string[])].sort(); const selectedPort = port || ports[0] || ''; const selectedRows = rows.filter((row) => !selectedPort || row.embark_port === selectedPort)
  const operation = useQuery({ queryKey: ['vazios-operation', voyageId, selectedPort], queryFn: () => getVaziosExportOperation(Number(voyageId), selectedPort), enabled: Boolean(voyageId && selectedPort) })
  const catalog = useQuery({ queryKey: ['vazios-catalog', selectedRows.map((row) => row.depot_id).sort().join(',')], queryFn: async () => { const ids = [...new Set(selectedRows.map((row) => row.depot_id).filter(Boolean) as string[])]; const depots = await listDepots(); const services = (await Promise.all(ids.map((id) => listCurrentDepotServices(id)))).flat(); return { depots: new Map(ids.map((id) => [id, depots.find((depot) => depot.id === id) ?? null] as const)), services } }, enabled: tab === 'costs' && selectedRows.length > 0 })
  const costs = catalog.data ? computeOperationTotals(selectedRows.map((row) => ({ container_number: row.container_number, depot_id: row.depot_id, hand_in_date: row.hand_in_date, hand_out_date: row.hand_out_date, overtime_pct: row.overtime_pct })), catalog.data.depots ?? new Map(), catalog.data.services ?? [], new Map((operation.data?.service_qty ?? []).map((row) => [row.depot_service_id, row.qty]))) : null

  async function previewFile(next: File | null) { setFile(next); if (!next) return setPreview(null); try { setPreview(await parseVaziosManifestFile(next)) } catch (error) { showToast(error instanceof Error ? error.message : 'Falha ao ler planilha.', 'error') } }
  async function submitImport() { if (!file || !preview || !user?.id || !voyageId || !uploadPort) return; try { await importVaziosManifest({ filename: file.name, voyageId: Number(voyageId), port: uploadPort, manifest: preview, uploadedBy: user.id }); showToast('Planilha importada.', 'success'); setImportOpen(false); setFile(null); setPreview(null); await queryClient.invalidateQueries({ queryKey: ['vazios-bookings'] }) } catch (error) { showToast(error instanceof Error ? error.message : 'Falha ao importar.', 'error') } }
  return <div className="grid gap-5"><PageHeader title="Vazios — Exportação" description="Containers vazios embarcados; o container é o grão operacional." action={<div className="flex flex-wrap gap-2"><Link className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#21262d] px-4 text-sm font-semibold text-slate-100" to="/embarquevazios/depots">Tabela de Depots</Link><a className="inline-flex h-10 items-center gap-2 rounded-lg bg-[#21262d] px-4 text-sm font-semibold text-slate-100" href="/templates/vazios-modelo.xlsx" download><Download size={16} /> Template</a>{canEdit ? <Button onClick={() => setImportOpen(true)}><Upload size={16} /> Importar</Button> : null}</div>} />
    <Card><div className="grid gap-3 md:grid-cols-3"><VoyageCombobox label="Viagem" selectedVoyageId={voyageId} onSelect={(id) => { setVoyageId(id == null ? '' : String(id)); setPort('') }} clearable /><Field label="Busca"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Booking ou container" /></Field><Field label="Porto"><Select value={selectedPort} onChange={(event) => setPort(event.target.value)}><option value="">Todos</option>{ports.map((item) => <option key={item} value={item}>{item}</option>)}</Select></Field></div><div className="mt-4 flex gap-2"><Button variant={tab === 'containers' ? 'primary' : 'secondary'} onClick={() => setTab('containers')}>Containers</Button><Button variant={tab === 'costs' ? 'primary' : 'secondary'} onClick={() => setTab('costs')}>Custos</Button></div></Card>
    {bookings.error ? <InlineError message="Erro ao carregar containers." /> : null}{!voyageId ? <EmptyState title="Selecione uma viagem" description="Escolha uma viagem para consultar os vazios embarcados." /> : null}
    {voyageId && tab === 'containers' ? <Card className="overflow-auto p-0"><table className="app-table w-full text-left text-sm"><thead><tr><th>Booking</th><th>Container</th><th>Tipo</th><th>Depot</th><th>Hand-in</th><th>Hand-out</th><th>Overtime</th><th>Condição</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>{row.booking_number || '—'}</td><td>{row.container_number}</td><td>{row.container_type || '—'}</td><td>{row.depot || 'Embarque Direto'}</td><td>{formatDate(row.hand_in_date)}</td><td>{formatDate(row.hand_out_date)}</td><td>{Number(row.overtime_pct ?? 0)}%</td><td>{row.condition || '—'}</td></tr>)}</tbody></table>{!rows.length ? <EmptyState title="Nenhum container encontrado" description="Importe uma planilha ou ajuste os filtros." /> : null}</Card> : null}
    {voyageId && tab === 'costs' ? <Card><div className="grid gap-4"><div className="flex items-center justify-between"><h2 className="app-panel__title">Custos da operação</h2><span className="text-xl font-semibold">{formatBRL(costs?.total ?? 0)}</span></div>{catalog.error ? <InlineError message="Erro ao carregar serviços do depot." /> : null}{catalog.data?.services.filter((service) => service.calc_type === 'quantidade').map((service) => { const saved = operation.data?.service_qty?.find((row) => row.depot_service_id === service.id)?.qty ?? 0; return <Field key={service.id} label={`${service.name} (quantidade)`}><Input type="number" min={0} value={qtyDrafts[service.id] ?? saved} disabled={!canEdit || !operation.data} onChange={(event) => setQtyDrafts((current) => ({ ...current, [service.id]: event.target.value }))} onBlur={() => { const qty = Number(qtyDrafts[service.id] ?? saved); if (operation.data?.id && Number.isInteger(qty) && qty >= 0) void upsertOperationServiceQty({ operationId: operation.data.id, depotServiceId: service.id, qty }).then(() => queryClient.invalidateQueries({ queryKey: ['vazios-operation', voyageId, selectedPort] })) }} /></Field> })}<table className="app-table w-full text-left text-sm"><thead><tr><th>Container</th><th>Fixos</th><th>Storage</th><th>Overtime</th><th>Total</th></tr></thead><tbody>{costs?.rows.map((row) => <tr key={row.container_number}><td>{row.container_number}</td><td>{formatBRL(row.fixed)}</td><td>{formatBRL(row.storage)}</td><td>{formatBRL(row.overtime)}</td><td>{formatBRL(row.total)}</td></tr>)}</tbody></table></div></Card> : null}
    <Modal open={importOpen} title="Importar Vazios EXP" onClose={() => setImportOpen(false)}><div className="grid gap-3"><Field label="Porto de embarque"><Input value={uploadPort} onChange={(event) => setUploadPort(event.target.value)} /></Field><Input type="file" accept=".xlsx,.xls,.csv" onChange={(event) => void previewFile(event.target.files?.[0] ?? null)} />{preview ? <p className="text-sm">{preview.bookings.length} linhas prontas; {preview.rowErrors.length} avisos.</p> : null}<Button disabled={!preview || !uploadPort || !voyageId} onClick={() => void submitImport()}>Confirmar importação</Button></div></Modal>
  </div>
}
