-- 022: inbox durável e processamento idempotente dos eventos do provedor.
--
-- O webhook só valida e persiste o envelope mínimo. A resolução da tentativa,
-- a transição do estado e as supressões acontecem numa transação privada; o
-- runner posterior faz apenas os efeitos secundários que podem falar com
-- APIs externas. Receber uma duplicata não equivale a concluir o evento.

ALTER TABLE public.portal_email_events
  ADD COLUMN IF NOT EXISTS provider_message_id text,
  ADD COLUMN IF NOT EXISTS payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS attempt_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS process_after timestamptz,
  ADD COLUMN IF NOT EXISTS lease_until timestamptz,
  ADD COLUMN IF NOT EXISTS leased_by text,
  ADD COLUMN IF NOT EXISTS processed_at timestamptz,
  ADD COLUMN IF NOT EXISTS last_error_code text,
  ADD COLUMN IF NOT EXISTS last_error_message text,
  ADD COLUMN IF NOT EXISTS processing_result jsonb NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

UPDATE public.portal_email_events
SET payload = '{}'::jsonb,
    status = 'investigate',
    last_error_code = 'legacy_event_without_payload',
    last_error_message = 'Evento recebido antes da inbox durável; replay do provedor deve ser avaliado.',
    updated_at = COALESCE(updated_at, received_at, now())
WHERE payload IS NULL OR payload = '{}'::jsonb AND status = 'pending';

UPDATE public.portal_email_events
SET provider_message_id = NULLIF(btrim(payload #>> '{data,email_id}'), '')
WHERE provider_message_id IS NULL
  AND NULLIF(btrim(payload #>> '{data,email_id}'), '') IS NOT NULL;

DO $constraints_022$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'portal_email_events_payload_object_check'
  ) THEN
    ALTER TABLE public.portal_email_events
      ADD CONSTRAINT portal_email_events_payload_object_check
      CHECK (jsonb_typeof(payload) = 'object');
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'portal_email_events_status_check'
  ) THEN
    ALTER TABLE public.portal_email_events
      ADD CONSTRAINT portal_email_events_status_check
      CHECK (status IN ('pending', 'processing', 'retry_wait', 'processed', 'failed', 'investigate'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'portal_email_events_attempt_count_check'
  ) THEN
    ALTER TABLE public.portal_email_events
      ADD CONSTRAINT portal_email_events_attempt_count_check
      CHECK (attempt_count >= 0);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'portal_email_events_lease_worker_check'
  ) THEN
    ALTER TABLE public.portal_email_events
      ADD CONSTRAINT portal_email_events_lease_worker_check
      CHECK (leased_by IS NULL OR char_length(btrim(leased_by)) BETWEEN 1 AND 160);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'portal_email_events_processing_result_object_check'
  ) THEN
    ALTER TABLE public.portal_email_events
      ADD CONSTRAINT portal_email_events_processing_result_object_check
      CHECK (jsonb_typeof(processing_result) = 'object');
  END IF;
END;
$constraints_022$;

CREATE INDEX IF NOT EXISTS idx_portal_email_events_inbox_claim
  ON public.portal_email_events (status, process_after, received_at, id)
  WHERE status IN ('pending', 'retry_wait', 'processing');

CREATE INDEX IF NOT EXISTS idx_portal_email_events_provider_message_id
  ON public.portal_email_events (provider_message_id)
  WHERE provider_message_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.portal_email_event_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id bigint NOT NULL REFERENCES public.portal_email_events(id) ON DELETE RESTRICT,
  attempt_no integer NOT NULL CHECK (attempt_no > 0),
  worker_id text NOT NULL CHECK (char_length(btrim(worker_id)) BETWEEN 1 AND 160),
  status text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  error_code text,
  error_message text,
  result jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(result) = 'object')
);

CREATE INDEX IF NOT EXISTS idx_portal_email_event_attempts_event
  ON public.portal_email_event_attempts (event_id, occurred_at DESC, id DESC);

CREATE OR REPLACE FUNCTION public._portal_email_event_attempts_append_only()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
BEGIN
  RAISE EXCEPTION 'Histórico de eventos de email é append-only.' USING ERRCODE = '55006';
END;
$$;

DROP TRIGGER IF EXISTS portal_email_event_attempts_append_only
  ON public.portal_email_event_attempts;
CREATE TRIGGER portal_email_event_attempts_append_only
  BEFORE UPDATE OR DELETE ON public.portal_email_event_attempts
  FOR EACH ROW EXECUTE FUNCTION public._portal_email_event_attempts_append_only();

-- Eventos antigos não têm payload recuperável. Eles ficam explicitamente em
-- investigação, em vez de serem tratados como processados ou replayados sem
-- evidência.
COMMENT ON COLUMN public.portal_email_events.payload IS
  'Envelope mínimo do provedor: type, data.email_id, data.to e data.bounce.type; contém PII e é privado.';
COMMENT ON COLUMN public.portal_email_events.status IS
  'Estado da inbox: pending, processing, retry_wait, processed, failed ou investigate.';

ALTER TABLE public.portal_email_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_email_event_attempts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS portal_email_events_internal_read ON public.portal_email_events;

REVOKE ALL ON TABLE public.portal_email_events FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE ON TABLE public.portal_email_events TO service_role;
REVOKE ALL ON TABLE public.portal_email_event_attempts FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.portal_email_event_attempts TO service_role;

REVOKE ALL ON FUNCTION public._portal_email_event_attempts_append_only() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public._portal_email_event_attempts_append_only() TO service_role;

CREATE OR REPLACE FUNCTION public.claim_portal_email_events(
  p_worker_id text,
  p_limit integer DEFAULT 50,
  p_lease_seconds integer DEFAULT 300
)
RETURNS SETOF public.portal_email_events
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_worker_id text := NULLIF(btrim(p_worker_id), '');
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'claim_portal_email_events exige service_role.' USING ERRCODE = '42501';
  END IF;
  IF v_worker_id IS NULL OR char_length(v_worker_id) > 160 THEN
    RAISE EXCEPTION 'worker_id inválido.' USING ERRCODE = '22023';
  END IF;
  IF p_limit IS NULL OR p_limit < 1 OR p_limit > 100 THEN
    RAISE EXCEPTION 'limit deve estar entre 1 e 100.' USING ERRCODE = '22023';
  END IF;
  IF p_lease_seconds IS NULL OR p_lease_seconds < 30 OR p_lease_seconds > 3600 THEN
    RAISE EXCEPTION 'lease_seconds deve estar entre 30 e 3600.' USING ERRCODE = '22023';
  END IF;

  -- Recupera crashes sem apagar a evidência. As seis tentativas são 1, 5,
  -- 15, 60 e 360 minutos; a sexta tentativa esgotada vai para investigação.
  WITH expired AS (
    UPDATE public.portal_email_events e
       SET status = CASE WHEN e.attempt_count >= 6 THEN 'investigate' ELSE 'retry_wait' END,
           process_after = CASE
             WHEN e.attempt_count >= 6 THEN NULL
             WHEN e.attempt_count = 1 THEN now() + interval '1 minute'
             WHEN e.attempt_count = 2 THEN now() + interval '5 minutes'
             WHEN e.attempt_count = 3 THEN now() + interval '15 minutes'
             WHEN e.attempt_count = 4 THEN now() + interval '60 minutes'
             ELSE now() + interval '360 minutes'
           END,
           lease_until = NULL,
           leased_by = NULL,
           last_error_code = 'lease_expired',
           last_error_message = 'Worker perdeu o lease antes de concluir o evento.',
           updated_at = now()
     WHERE e.status = 'processing'
       AND e.lease_until IS NOT NULL
       AND e.lease_until < now()
     RETURNING e.id, e.attempt_count, e.status, e.last_error_code, e.last_error_message
  )
  INSERT INTO public.portal_email_event_attempts (
    event_id, attempt_no, worker_id, status, error_code, error_message
  )
  SELECT id, GREATEST(attempt_count, 1), v_worker_id, status, last_error_code, last_error_message
  FROM expired;

  RETURN QUERY
  WITH candidates AS (
    SELECT e.id
      FROM public.portal_email_events e
     WHERE (
       e.status = 'pending'
       OR (e.status = 'retry_wait' AND COALESCE(e.process_after, now()) <= now())
     )
     ORDER BY e.received_at, e.id
     LIMIT p_limit
     FOR UPDATE SKIP LOCKED
  ), claimed AS (
    UPDATE public.portal_email_events e
       SET status = 'processing',
           attempt_count = e.attempt_count + 1,
           lease_until = now() + make_interval(secs => p_lease_seconds),
           leased_by = v_worker_id,
           process_after = NULL,
           last_error_code = NULL,
           last_error_message = NULL,
           updated_at = now()
      FROM candidates c
     WHERE e.id = c.id
     RETURNING e.*
  ), logged AS (
    INSERT INTO public.portal_email_event_attempts (
      event_id, attempt_no, worker_id, status
    )
    SELECT id, attempt_count, v_worker_id, status FROM claimed
  )
  SELECT c.* FROM claimed c;
END;
$$;

CREATE OR REPLACE FUNCTION public.complete_portal_email_event(
  p_event_id bigint,
  p_worker_id text,
  p_status text,
  p_error_code text DEFAULT NULL,
  p_error_message text DEFAULT NULL,
  p_retry_at timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_event public.portal_email_events%ROWTYPE;
  v_worker_id text := NULLIF(btrim(p_worker_id), '');
  v_status text := NULLIF(btrim(p_status), '');
  v_retry_at timestamptz;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'complete_portal_email_event exige service_role.' USING ERRCODE = '42501';
  END IF;
  IF p_event_id IS NULL OR v_worker_id IS NULL OR v_status IS NULL THEN
    RAISE EXCEPTION 'event_id, worker_id e status são obrigatórios.' USING ERRCODE = '22023';
  END IF;
  IF v_status NOT IN ('processed', 'retry_wait', 'failed', 'investigate') THEN
    RAISE EXCEPTION 'status de conclusão inválido.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_event
    FROM public.portal_email_events
   WHERE id = p_event_id
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Evento de email não encontrado.' USING ERRCODE = 'P0002';
  END IF;

  IF v_event.status = 'processed' THEN
    RETURN jsonb_build_object('event_id', v_event.id, 'status', 'processed', 'idempotent', true);
  END IF;
  IF v_event.status <> 'processing'
     OR v_event.leased_by IS DISTINCT FROM v_worker_id
     OR v_event.lease_until IS NULL
     OR v_event.lease_until < now() THEN
    RAISE EXCEPTION 'Lease do evento não pertence ao worker ou expirou.' USING ERRCODE = '40001';
  END IF;

  v_retry_at := CASE
    WHEN v_status = 'retry_wait' THEN COALESCE(
      p_retry_at,
      now() + CASE v_event.attempt_count
        WHEN 1 THEN interval '1 minute'
        WHEN 2 THEN interval '5 minutes'
        WHEN 3 THEN interval '15 minutes'
        WHEN 4 THEN interval '60 minutes'
        ELSE interval '360 minutes'
      END
    )
    ELSE NULL
  END;

  UPDATE public.portal_email_events
     SET status = v_status,
         process_after = v_retry_at,
         processed_at = CASE WHEN v_status = 'processed' THEN now() ELSE NULL END,
         lease_until = NULL,
         leased_by = NULL,
         last_error_code = NULLIF(btrim(p_error_code), ''),
         last_error_message = NULLIF(btrim(p_error_message), ''),
         processing_result = processing_result || jsonb_build_object('status', v_status),
         updated_at = now()
   WHERE id = p_event_id;

  INSERT INTO public.portal_email_event_attempts (
    event_id, attempt_no, worker_id, status, error_code, error_message, result
  ) VALUES (
    v_event.id, v_event.attempt_count, v_worker_id, v_status,
    NULLIF(btrim(p_error_code), ''), NULLIF(btrim(p_error_message), ''),
    v_event.processing_result || jsonb_build_object('status', v_status)
  );

  RETURN jsonb_build_object(
    'event_id', p_event_id,
    'status', v_status,
    'retry_at', v_retry_at,
    'idempotent', false
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.process_portal_email_event(
  p_event_id bigint,
  p_worker_id text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, pg_temp
AS $$
DECLARE
  v_event public.portal_email_events%ROWTYPE;
  v_worker_id text := NULLIF(btrim(p_worker_id), '');
  v_provider_message_id text;
  v_email text;
  v_next_status text;
  v_event_kind text;
  v_bounce_type text;
  v_permanent_bounce boolean := false;
  v_portal_count integer := 0;
  v_communication_count integer := 0;
  v_portal_attempt_id bigint;
  v_communication_attempt_id bigint;
  v_communication_id bigint;
  v_portal_account_id bigint;
  v_portal_kind text;
  v_attempt_status text;
  v_stale boolean := false;
  v_customer_id bigint;
  v_customer_ids jsonb := '[]'::jsonb;
  v_result jsonb;
  v_retry_status text;
  v_retry_at timestamptz;
BEGIN
  IF auth.role() <> 'service_role' THEN
    RAISE EXCEPTION 'process_portal_email_event exige service_role.' USING ERRCODE = '42501';
  END IF;
  IF p_event_id IS NULL OR v_worker_id IS NULL THEN
    RAISE EXCEPTION 'event_id e worker_id são obrigatórios.' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_event
    FROM public.portal_email_events
   WHERE id = p_event_id
   FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Evento de email não encontrado.' USING ERRCODE = 'P0002';
  END IF;
  IF v_event.status IN ('processed', 'investigate', 'failed') THEN
    RETURN COALESCE(v_event.processing_result, '{}'::jsonb)
      || jsonb_build_object('event_id', v_event.id, 'status', v_event.status, 'idempotent', true);
  END IF;
  IF v_event.status <> 'processing'
     OR v_event.leased_by IS DISTINCT FROM v_worker_id
     OR v_event.lease_until IS NULL
     OR v_event.lease_until < now() THEN
    RAISE EXCEPTION 'Lease do evento não pertence ao worker ou expirou.' USING ERRCODE = '40001';
  END IF;

  v_event_kind := lower(btrim(v_event.event_type));
  v_provider_message_id := NULLIF(btrim(COALESCE(
    v_event.provider_message_id,
    v_event.payload #>> '{data,email_id}'
  )), '');
  v_email := NULLIF(lower(btrim(COALESCE(
    v_event.payload #>> '{data,to,0}',
    v_event.payload->>'recipient'
  ))), '');
  v_bounce_type := lower(btrim(COALESCE(v_event.payload #>> '{data,bounce,type}', '')));
  v_permanent_bounce := v_event_kind = 'email.bounced' AND v_bounce_type = 'permanent';

  IF v_event_kind NOT IN ('email.delivered', 'email.bounced', 'email.complained') THEN
    v_result := jsonb_build_object(
      'event_id', v_event.id,
      'status', 'processing',
      'processed', true,
      'ignored_unknown_event', true
    );
    UPDATE public.portal_email_events
       SET processing_result = v_result,
           updated_at = now()
     WHERE id = v_event.id;
    RETURN v_result;
  END IF;

  IF v_provider_message_id IS NOT NULL THEN
    SELECT count(*) INTO v_portal_count
      FROM public.portal_email_attempts
     WHERE provider_message_id = v_provider_message_id;
    SELECT count(*) INTO v_communication_count
      FROM public.customer_communication_attempts
     WHERE provider_message_id = v_provider_message_id;
  END IF;

  IF v_portal_count + v_communication_count > 1 THEN
    v_retry_status := 'investigate';
    v_retry_at := NULL;
    UPDATE public.portal_email_events
       SET status = v_retry_status,
           process_after = v_retry_at,
           lease_until = NULL,
           leased_by = NULL,
           last_error_code = 'ambiguous_provider_message_id',
           last_error_message = 'Provider message id corresponde a mais de uma tentativa.',
           processing_result = jsonb_build_object(
             'event_id', v_event.id,
             'status', v_retry_status,
             'provider_message_id', v_provider_message_id
           ),
           updated_at = now()
     WHERE id = v_event.id;
    INSERT INTO public.portal_email_event_attempts (
      event_id, attempt_no, worker_id, status, error_code, error_message, result
    ) VALUES (
      v_event.id, v_event.attempt_count, v_worker_id, v_retry_status,
      'ambiguous_provider_message_id', 'Provider message id corresponde a mais de uma tentativa.',
      jsonb_build_object('provider_message_id', v_provider_message_id)
    );
    RETURN jsonb_build_object(
      'event_id', v_event.id,
      'status', v_retry_status,
      'provider_message_id', v_provider_message_id
    );
  END IF;

  -- Um evento já aplicado pode ser reprocessado após crash no efeito
  -- secundário. Mantemos a referência original e tornamos o bloco idempotente.
  v_portal_attempt_id := v_event.attempt_id;
  v_communication_attempt_id := v_event.communication_attempt_id;
  IF v_portal_attempt_id IS NULL AND v_communication_attempt_id IS NULL AND v_provider_message_id IS NOT NULL THEN
    IF v_portal_count = 1 THEN
      SELECT id, account_id, kind
        INTO v_portal_attempt_id, v_portal_account_id, v_portal_kind
        FROM public.portal_email_attempts
       WHERE provider_message_id = v_provider_message_id;
    ELSIF v_communication_count = 1 THEN
      SELECT a.id, a.communication_id
        INTO v_communication_attempt_id, v_communication_id
        FROM public.customer_communication_attempts a
       WHERE a.provider_message_id = v_provider_message_id;
    END IF;
  END IF;

  IF v_portal_attempt_id IS NOT NULL THEN
    SELECT account_id, kind, status
      INTO v_portal_account_id, v_portal_kind, v_attempt_status
      FROM public.portal_email_attempts
     WHERE id = v_portal_attempt_id;
    v_stale := EXISTS (
      SELECT 1 FROM public.portal_email_events older
       WHERE older.attempt_id = v_portal_attempt_id
         AND older.status = 'processed'
         AND older.received_at > v_event.received_at
    );
  ELSIF v_communication_attempt_id IS NOT NULL THEN
    SELECT communication_id, status
      INTO v_communication_id, v_attempt_status
      FROM public.customer_communication_attempts
     WHERE id = v_communication_attempt_id;
    v_stale := EXISTS (
      SELECT 1 FROM public.portal_email_events older
       WHERE older.communication_attempt_id = v_communication_attempt_id
         AND older.status = 'processed'
         AND older.received_at > v_event.received_at
    );
  END IF;

  IF v_portal_attempt_id IS NULL AND v_communication_attempt_id IS NULL THEN
    IF v_event.attempt_count >= 6 THEN
      v_retry_status := 'investigate';
      v_retry_at := NULL;
    ELSE
      v_retry_status := 'retry_wait';
      v_retry_at := now() + CASE v_event.attempt_count
        WHEN 1 THEN interval '1 minute'
        WHEN 2 THEN interval '5 minutes'
        WHEN 3 THEN interval '15 minutes'
        WHEN 4 THEN interval '60 minutes'
        ELSE interval '360 minutes'
      END;
    END IF;
    v_result := jsonb_build_object(
      'event_id', v_event.id,
      'status', v_retry_status,
      'provider_message_id', v_provider_message_id,
      'error_code', 'attempt_unresolved'
    );
    UPDATE public.portal_email_events
       SET status = v_retry_status,
           process_after = v_retry_at,
           lease_until = NULL,
           leased_by = NULL,
           last_error_code = 'attempt_unresolved',
           last_error_message = 'Tentativa ainda não possui provider_message_id vinculado.',
           processing_result = v_result,
           updated_at = now()
     WHERE id = v_event.id;
    INSERT INTO public.portal_email_event_attempts (
      event_id, attempt_no, worker_id, status, error_code, error_message, result
    ) VALUES (
      v_event.id, v_event.attempt_count, v_worker_id, v_retry_status,
      'attempt_unresolved', 'Tentativa ainda não possui provider_message_id vinculado.', v_result
    );
    IF v_retry_status = 'investigate' THEN
      PERFORM public.block521_upsert_alert(
        'portal_reprocessamento_falhou',
        'portal_email_event',
        v_event.id::text,
        'Evento de email recebido sem tentativa vinculada após o limite de retry; investigue no provedor.',
        'portal_email_events_runner',
        'documentacao',
        jsonb_build_object('event_id', v_event.id, 'provider_message_id', v_provider_message_id),
        '/clientes/portal'
      );
    END IF;
    RETURN v_result;
  END IF;

  v_next_status := CASE v_event_kind
    WHEN 'email.delivered' THEN 'entregue'
    WHEN 'email.bounced' THEN 'bounce'
    WHEN 'email.complained' THEN 'complaint'
  END;

  IF v_portal_attempt_id IS NOT NULL THEN
    IF NOT v_stale AND NOT (
      v_attempt_status IN ('bounce', 'complaint', 'falha_permanente')
      AND v_next_status <> v_attempt_status
    ) THEN
      UPDATE public.portal_email_attempts
         SET status = v_next_status,
             updated_at = now()
       WHERE id = v_portal_attempt_id;
    END IF;
    UPDATE public.portal_email_events
       SET attempt_id = v_portal_attempt_id,
           communication_attempt_id = NULL
     WHERE id = v_event.id;
  ELSE
    IF NOT v_stale AND NOT (
      v_attempt_status IN ('bounce', 'complaint', 'falha_permanente')
      AND v_next_status <> v_attempt_status
    ) THEN
      UPDATE public.customer_communication_attempts
         SET status = v_next_status,
             updated_at = now()
       WHERE id = v_communication_attempt_id;
    END IF;
    UPDATE public.portal_email_events
       SET communication_attempt_id = v_communication_attempt_id,
           attempt_id = NULL
     WHERE id = v_event.id;
  END IF;

  -- Fatos de supressão e saúde do endereço são internos e idempotentes. O
  -- aviso ao cliente e o reparo de caixas ficam para o runner após o commit.
  IF v_email IS NOT NULL AND v_permanent_bounce THEN
    INSERT INTO public.portal_suppressed_emails (email, reason, suppressed_at)
    VALUES (v_email, 'bounce_permanente', now())
    ON CONFLICT (email) DO UPDATE
      SET reason = 'bounce_permanente', suppressed_at = EXCLUDED.suppressed_at;
  ELSIF v_email IS NOT NULL AND v_event_kind = 'email.complained' AND v_portal_attempt_id IS NOT NULL THEN
    INSERT INTO public.portal_suppressed_emails (email, reason, suppressed_at)
    VALUES (v_email, 'complaint', now())
    ON CONFLICT (email) DO NOTHING;
  ELSIF v_email IS NOT NULL AND v_event_kind = 'email.complained' AND v_communication_attempt_id IS NOT NULL THEN
    INSERT INTO public.customer_communication_suppressions (email, reason, suppressed_at)
    VALUES (v_email, 'complaint', now())
    ON CONFLICT (email) DO NOTHING;
  END IF;

  IF v_portal_attempt_id IS NOT NULL
     AND v_portal_kind IS DISTINCT FROM 'contato_bounced_notificacao'
     AND v_event_kind IN ('email.bounced', 'email.complained') THEN
    UPDATE public.customer_portal_accounts
       SET recovery_email_status = CASE WHEN v_event_kind = 'email.bounced' THEN 'bounce_permanente' ELSE 'complaint' END,
           account_situation = CASE WHEN account_situation = 'convite_pendente' THEN 'falha_no_envio' ELSE account_situation END
     WHERE id = v_portal_account_id
        OR (v_email IS NOT NULL AND lower(btrim(recovery_email)) = v_email);
  END IF;

  SELECT COALESCE(jsonb_agg(customer_id ORDER BY customer_id), '[]'::jsonb)
    INTO v_customer_ids
    FROM (
      SELECT DISTINCT a.customer_id
        FROM public.customer_portal_accounts a
       WHERE a.id = v_portal_account_id
      UNION
      SELECT DISTINCT a.customer_id
        FROM public.customer_portal_accounts a
       WHERE v_email IS NOT NULL AND lower(btrim(a.recovery_email)) = v_email
      UNION
      SELECT DISTINCT c.customer_id
        FROM public.customer_communications c
       WHERE c.id = v_communication_id
      UNION
      SELECT DISTINCT cc.customer_id
        FROM public.customer_contacts cc
       WHERE v_email IS NOT NULL AND cc.email_normalized = v_email
    ) customers;

  IF v_permanent_bounce
     AND v_portal_kind IS DISTINCT FROM 'contato_bounced_notificacao' THEN
    -- O reparo de caixas é escrita de domínio, não efeito HTTP. Executá-lo
    -- aqui mantém supressão, conta e fallback na mesma transação do evento.
    FOR v_customer_id IN
      SELECT value::bigint FROM jsonb_array_elements_text(v_customer_ids)
    LOOP
      PERFORM public.repair_customer_contact_box_fallbacks(v_customer_id);
    END LOOP;
  END IF;

  IF v_portal_attempt_id IS NOT NULL
     AND v_portal_kind IS DISTINCT FROM 'contato_bounced_notificacao'
     AND v_event_kind IN ('email.bounced', 'email.complained') THEN
    FOR v_customer_id IN
      SELECT DISTINCT a.customer_id
        FROM public.customer_portal_accounts a
       WHERE a.id = v_portal_account_id
          OR (v_email IS NOT NULL AND lower(btrim(a.recovery_email)) = v_email)
    LOOP
      PERFORM public.block521_upsert_alert(
        'portal_email_suprimido',
        'customer',
        v_customer_id::text,
        'Email de Recuperação indisponível. Informe ou valide outro endereço.',
        'portal_email_events_runner',
        'documentacao',
        jsonb_build_object('customer_id', v_customer_id, 'email', v_email),
        '/clientes/portal?cliente=' || v_customer_id
      );
    END LOOP;
  END IF;

  v_result := jsonb_build_object(
    'event_id', v_event.id,
    'status', 'processing',
    'processed', true,
    'provider_message_id', v_provider_message_id,
    'email', v_email,
    'event_type', v_event_kind,
    'portal_attempt_id', v_portal_attempt_id,
    'communication_attempt_id', v_communication_attempt_id,
    'permanent_bounce', v_permanent_bounce,
    'portal_recovery_attempt', v_portal_attempt_id IS NOT NULL AND v_portal_kind IS DISTINCT FROM 'contato_bounced_notificacao',
    'should_cascade', v_permanent_bounce AND v_portal_kind IS DISTINCT FROM 'contato_bounced_notificacao',
    'customer_ids', v_customer_ids,
    'stale_transition_ignored', v_stale
  );

  UPDATE public.portal_email_events
     SET processing_result = v_result,
         updated_at = now()
   WHERE id = v_event.id;

  INSERT INTO public.portal_email_event_attempts (
    event_id, attempt_no, worker_id, status, result
  ) VALUES (v_event.id, v_event.attempt_count, v_worker_id, 'processing', v_result);

  RETURN v_result;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_portal_email_events(text, integer, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.complete_portal_email_event(bigint, text, text, text, text, timestamptz) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.process_portal_email_event(bigint, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_portal_email_events(text, integer, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.complete_portal_email_event(bigint, text, text, text, text, timestamptz) TO service_role;
GRANT EXECUTE ON FUNCTION public.process_portal_email_event(bigint, text) TO service_role;

DO $schedule_022$
BEGIN
  IF to_regclass('cron.job') IS NOT NULL
     AND to_regproc('ops.dispatch_edge_job(text,text,text,text)') IS NOT NULL THEN
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'portal-email-events-runner') THEN
      PERFORM cron.unschedule('portal-email-events-runner');
    END IF;
    PERFORM cron.schedule(
      'portal-email-events-runner',
      '* * * * *',
      $$SELECT ops.dispatch_edge_job('portal-email-events-runner', 'PORTAL_EMAIL_EVENTS_CRON_SECRET');$$
    );
  ELSE
    RAISE WARNING '022: pg_cron/ops.dispatch_edge_job ausente; agende portal-email-events-runner no ambiente de produção.';
  END IF;
END;
$schedule_022$;
