import { Link } from 'react-router-dom'
import { Card } from '../ui/Card'
import { MetricCard } from '../ui/MetricCard'
import { usePortalProvisioningForCustomer } from '../../hooks/usePortalProvisioning'
import { accountSituationLabel } from '../../lib/portalProvisioningViewModel'
import { useCustomerDemurrageInvoices, useCustomerPendingReconciliation, useCustomerRunningDemurrage, useCustomerTimeline } from '../../hooks/useCustomerFicha'
import { buildConsolidatedBalance } from '../../services/customerFicha'
import { formatBRL, formatCnpjCpf, formatDate } from '../../lib/utils'
import type { useCustomerDetail } from '../../hooks/useCustomers'
import type { FichaTabId } from './fichaTabConfig'

type Data = NonNullable<ReturnType<typeof useCustomerDetail>['data']>
export function VisaoGeralTab({ data, onNavigateTab }: { data: Data; onNavigateTab: (tab: FichaTabId) => void }) {
  const { data: portalRow } = usePortalProvisioningForCustomer(data.id); const { data: demurrage } = useCustomerDemurrageInvoices(data.id); const { data: pending } = useCustomerPendingReconciliation(data.id); const { data: running } = useCustomerRunningDemurrage(data.id); const { data: timeline } = useCustomerTimeline(data.id, data.customer_contacts ?? [], data.bls ?? [])
  const denied = Boolean(data.invoices_access_denied || demurrage?.denied); const balance = buildConsolidatedBalance(data.invoices ?? [], demurrage?.rows ?? []); const today = new Date().toISOString().slice(0, 10)
  const overdue = [...(data.invoices ?? []).filter((row) => row.status === 'issued' && row.due_date && row.due_date < today), ...(demurrage?.rows ?? []).filter((row) => row.status === 'overdue')]; const disputes = (demurrage?.rows ?? []).filter((row) => row.dispute_open || row.dispute_status === 'aberto')
  const pendencias: Array<{ key: string; label: string; to?: string; onClick?: () => void }> = []
  if (pending?.length) pendencias.push({ key: 'reconciliacao', label: `${pending.length} B/L(s) com reconciliação de cliente pendente`, onClick: () => onNavigateTab('operacional') })
  if (portalRow && portalRow.account_situation !== 'ativo') pendencias.push({ key: 'portal', label: `Portal não ativo: ${accountSituationLabel(portalRow.account_situation)}`, to: `/clientes/portal?cliente=${data.id}` })
  if (!denied && overdue.length) pendencias.push({ key: 'vencidas', label: `${overdue.length} invoice(s) vencida(s)`, onClick: () => onNavigateTab('financeiro') })
  if (!denied && disputes.length) pendencias.push({ key: 'disputas', label: `${disputes.length} disputa(s) de demurrage aberta(s)`, onClick: () => onNavigateTab('financeiro') })
  if (running?.length) pendencias.push({ key: 'correndo', label: `${running.length} container(s) com demurrage correndo`, to: '/demurrage' })
  return <><div className="mb-6 grid grid-cols-1 gap-4 sm:grid-cols-3"><MetricCard label="Saldo pendente (local + demurrage)" value={denied ? 'Restrito' : formatBRL(balance.totalBrl)} tone="primary" /><MetricCard label="Local" value={denied ? '—' : formatBRL(balance.localBrl)} /><MetricCard label="Demurrage" value={denied ? '—' : formatBRL(balance.demurrageBrl)} /></div><div className="grid gap-5 xl:grid-cols-2"><Card><h2 className="mb-4 text-lg font-semibold text-white">Identidade</h2><dl className="grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-xs text-slate-500">CNPJ/CPF</dt><dd>{formatCnpjCpf(data.cnpj_cpf)}</dd></div><div><dt className="text-xs text-slate-500">Cidade/UF</dt><dd>{[data.city, data.state].filter(Boolean).join(' / ') || '—'}</dd></div><div><dt className="text-xs text-slate-500">Contato principal</dt><dd>{data.customer_contacts?.find((row) => row.is_primary)?.name ?? data.customer_contacts?.[0]?.name ?? 'Nenhum contato'}</dd></div><div><dt className="text-xs text-slate-500">Portal</dt><dd>{portalRow ? accountSituationLabel(portalRow.account_situation) : '—'}</dd></div><div><dt className="text-xs text-slate-500">B/Ls vinculados</dt><dd>{data.bls?.length ?? 0}</dd></div></dl></Card><Card><h2 className="mb-4 text-lg font-semibold text-white">Pendências</h2>{pendencias.length ? <ul className="grid gap-2 text-sm">{pendencias.map((item) => <li key={item.key} className="rounded-xl border border-amber-400/30 bg-amber-950/30 px-3 py-2 text-amber-100">{item.to ? <Link to={item.to}>{item.label} →</Link> : <button type="button" className="text-left" onClick={item.onClick}>{item.label} →</button>}</li>)}</ul> : <div className="text-sm text-slate-400">Nenhuma pendência aberta.</div>}</Card></div><Card className="mt-5"><h2 className="mb-4 text-lg font-semibold text-white">Atividade recente</h2>{timeline?.length ? <ul className="grid gap-2 text-sm">{timeline.slice(0, 5).map((event) => <li key={`${event.kind}-${event.at}-${event.label}`}><span className="mr-3 text-xs text-slate-500">{formatDate(event.at)}</span>{event.link ? <Link to={event.link}>{event.label}</Link> : event.label}</li>)}</ul> : <div className="text-sm text-slate-400">Sem eventos registrados.</div>}</Card></>
}
